INSERT INTO categories (name)
VALUES
  ('Resistor'),
  ('Kapasitor'),
  ('Induktor & Coil'),
  ('Dioda'),
  ('Transistor'),
  ('IC & Integrated Circuit'),
  ('Mikrokontroler'),
  ('Sensor'),
  ('Modul Elektronik'),
  ('LED & Display'),
  ('Relay'),
  ('Switch & Push Button'),
  ('Connector'),
  ('Kabel'),
  ('Power Supply'),
  ('Baterai & Battery Holder'),
  ('PCB'),
  ('Potensiometer'),
  ('Kristal & Oscillator'),
  ('Fuse & Protection'),
  ('Motor & Aktuator'),
  ('Komponen SMD'),
  ('Komponen Elektronik Lainnya');